# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Faultline < Formula
  desc "Structural risk analysis for Go codebases"
  homepage "https://github.com/faultline-go/faultline"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faultline-go/faultline/releases/download/v0.1.0/faultline_0.1.0_darwin_amd64.tar.gz"
      sha256 "320436729f977dec592fe4498137909e5fc1a278aa221388d772f352d94607ed"

      define_method(:install) do
        bin.install "faultline"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faultline-go/faultline/releases/download/v0.1.0/faultline_0.1.0_darwin_arm64.tar.gz"
      sha256 "36b1520a727ef24eb1402696f0ae859591dacaade3be29832bb33f450e519fea"

      define_method(:install) do
        bin.install "faultline"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faultline-go/faultline/releases/download/v0.1.0/faultline_0.1.0_linux_amd64.tar.gz"
      sha256 "129c345eba65410175398abe5064ab42da3f3920ed0bdfefce86997484ed72dd"
      define_method(:install) do
        bin.install "faultline"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faultline-go/faultline/releases/download/v0.1.0/faultline_0.1.0_linux_arm64.tar.gz"
      sha256 "293fc7bc6275014ad51d8921741dc0fcfe196384e94c6e431271eb02795b3d01"
      define_method(:install) do
        bin.install "faultline"
      end
    end
  end

  test do
    system "#{bin}/faultline", "version"
  end
end
