# This file was generated by GoReleaser. DO NOT EDIT.
cask "faultline" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "edf799e08ceb7968ce15bed2299b69747ca8f4562f8ac0b5caeb757e406f8229"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e56cac8f49bff60180fd3bfba5950afbf1cc14f86f46fdee0ee5c4c71802cff9"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18d08fa8f0f754429e65835a78d8663b380f113661ab53327cb920ef55421c57"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e7ce856c5af6baff15fcf168c42f9670cdb912a4e7ea6b2c87ddab560fa6b125"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "faultline"
  desc "Structural risk analysis for Go codebases"
  homepage "https://github.com/faultline-go/faultline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "faultline"

  # No zap stanza required

end
