# This file was generated by GoReleaser. DO NOT EDIT.
cask "faultline" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "2bee2ff324278db5e53db09415ba7f7f99513b59ab152fe01f00ef4b5b941b39"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "677ae5275d6ee3adfb7aa68d02728b70f46383ff9e90ba431b97ee71ef793c76"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "abccabd6b33bf4e04742abfeb965494a3d97147dd884529d4fcdf4e6bcc6667d"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9230306b3f8d3a78c1022346134fe62b550aed7ec07246ef34723c2e8d115a86"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "faultline"
  desc "Structural risk analysis for Go codebases"
  homepage "https://github.com/faultline-go/faultline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "faultline"

  # No zap stanza required

end
