# This file was generated by GoReleaser. DO NOT EDIT.
cask "faultline" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "9f235ef2e7d2ec33394dd7f9a60fd18a8ed58b89ee69c800347dafaa3608ee78"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "16206454f9d8564afcffd933ba5c082dfef9e2cd0e5404137488d83409b20478"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0dffc91cf97de5055a881d068f7b69868906b7617331516cc547014e57dd655a"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a8b8ad58a439aab9c6e2e6d7581100a8c1123eb48210e6f86b8474d5782f3854"
      url "https://github.com/faultline-go/faultline/releases/download/v#{version}/faultline_#{version}_linux_arm64.tar.gz"
    end
  end

  name "faultline"
  desc "Structural risk analysis for Go codebases"
  homepage "https://github.com/faultline-go/faultline"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "faultline"

  # No zap stanza required

end
